#!/usr/bin/env Rscript
# =============================================================================
# export_geojson.R -- turn the repo's boundary files into apps/rcds-map-builder/
# data.js, which the static site loads to draw REAL geometry.
#
# Run from the repo root:
#   Rscript apps/rcds-map-builder/prep/export_geojson.R
# Requires: sf, rmapshaper   (install.packages(c("sf","rmapshaper")))
#
# The site auto-discovers numeric columns per layer, so whatever fields exist in
# the files below become mappable. Edit the DATASETS list to point at the files
# (and the columns) you want. _demog files usually carry raw percentages;
# _std files carry z-scores.
# =============================================================================

suppressPackageStartupMessages(library(sf))
has_ms <- requireNamespace("rmapshaper", quietly = TRUE)
if (!has_ms) message("note: install 'rmapshaper' for smaller files (geometry won't be simplified without it).")

# --- EDIT ME: site dataset id -> boundary file (+ simplify keep fraction) -----
DATASETS <- list(
  es       = list(path = "data/prep/gcps_es_demog.gpkg",                  keep = 0.08),
  ms       = list(path = "data/prep/gcps_ms_demog.gpkg",                  keep = 0.10),
  hs       = list(path = "data/prep/gcps_hs_demog.gpkg",                  keep = 0.10),
  metro_es = list(path = "data/prep/metro_es_absm.gpkg",                  keep = 0.05),
  tracts   = list(path = "data/prep/metro_tract_seg_2020_acs5yr_geo.rds", keep = 0.04),
  outline  = list(path = "data/prep/gcps_outline.gpkg",                   keep = 0.10),
  counties = list(path = "data/prep/counties.gpkg",                       keep = 0.06)
)

OUT <- "apps/rcds-map-builder/data.js"

read_any <- function(path) {
  if (grepl("\\.rds$", path, ignore.case = TRUE)) readRDS(path) else sf::st_read(path, quiet = TRUE)
}

emit <- character()
for (id in names(DATASETS)) {
  cfg <- DATASETS[[id]]
  if (!file.exists(cfg$path)) { message("skip ", id, ": missing ", cfg$path); next }
  x <- tryCatch(read_any(cfg$path),
                error = function(e) { message("skip ", id, ": ", conditionMessage(e)); NULL })
  if (is.null(x) || !inherits(x, "sf")) { message("skip ", id, ": not an sf layer"); next }

  x <- sf::st_zm(x, drop = TRUE, what = "ZM")
  x <- suppressWarnings(sf::st_make_valid(x))
  x <- sf::st_transform(x, 4326)
  if (has_ms) x <- tryCatch(rmapshaper::ms_simplify(x, keep = cfg$keep, keep_shapes = TRUE),
                            error = function(e) x)

  geom_col <- attr(x, "sf_column")
  message(sprintf("%-9s %4d features | columns: %s", id, nrow(x),
                  paste(setdiff(names(x), geom_col), collapse = ", ")))

  tmp <- tempfile(fileext = ".geojson")
  suppressWarnings(sf::st_write(
    x, tmp, driver = "GeoJSON", delete_dsn = TRUE, quiet = TRUE,
    layer_options = c("COORDINATE_PRECISION=5", "RFC7946=YES")))
  gj <- paste(readLines(tmp, warn = FALSE), collapse = "")
  emit <- c(emit, sprintf('  "%s": %s', id, gj))
}

dir.create(dirname(OUT), showWarnings = FALSE, recursive = TRUE)
con <- file(OUT, "w", encoding = "UTF-8")
writeLines("// Generated by prep/export_geojson.R -- do not edit by hand.", con)
writeLines("window.RCDS_GEODATA = {", con)
writeLines(paste(emit, collapse = ",\n"), con)
writeLines("};", con)
close(con)
message("Wrote ", OUT, " (", length(emit), " datasets). Commit data.js and reload the page.")
