// Ported from project/MetroPoster.dc.html (default theme) and
// project/Metro Atlanta School Districts.dc.html (themeB, themeC).

export const themeA = {
  id: '1a',
  label: '1a',
  name: 'Paper / editorial',
  blurb: 'Refined maroon, Spectral serif',
  bg: '#EFE9DC',
  panel: 'transparent',
  panelEdge: 'transparent',
  distFill: '#F4EFE3',
  distStroke: '#D6CDBA',
  distSW: 1.1,
  accent: '#8C2F39',
  accentDark: '#581E25',
  hiSW: 1.6,
  ink: '#2B2722',
  sub: '#6E665A',
  faint: '#9A9080',
  header: '#2B2722',
  num: '#A0937C',
  numHalo: '#EFE9DC',
  insetFill: '#E7DFCD',
  insetStroke: '#CDC3AD',
  titleFont: "'Spectral', Georgia, serif",
  titleWeight: 700,
  titleSize: 52,
  titleTransform: 'none',
  titleSpacing: '-0.5px',
  bodyFont: "'IBM Plex Sans', system-ui, sans-serif",
  monoFont: "'IBM Plex Mono', ui-monospace, monospace",
  hiLabel: '#581E25',
  hiHalo: '#EFE9DC',
  shadow: 'none',
};

export const themeB = {
  id: '1b',
  label: '1b',
  name: 'Civic / light',
  blurb: 'Deep-blue accent, Archivo grotesque',
  bg: '#EEF1F5',
  panel: 'transparent',
  panelEdge: 'transparent',
  distFill: '#FFFFFF',
  distStroke: '#D9DFE7',
  distSW: 1.1,
  accent: '#1F5C8B',
  accentDark: '#123F61',
  hiSW: 1.6,
  ink: '#1A2330',
  sub: '#5B6675',
  faint: '#93A0B0',
  header: '#15202E',
  num: '#9AA7B6',
  numHalo: '#FFFFFF',
  insetFill: '#E2E7EE',
  insetStroke: '#C7D0DB',
  titleFont: "'Archivo', system-ui, sans-serif",
  titleWeight: 700,
  titleSize: 49,
  titleTransform: 'none',
  titleSpacing: '-0.4px',
  bodyFont: "'Archivo', system-ui, sans-serif",
  monoFont: "'IBM Plex Mono', ui-monospace, monospace",
  hiLabel: '#123F61',
  hiHalo: '#EEF1F5',
  shadow: 'none',
};

export const themeC = {
  id: '1c',
  label: '1c',
  name: 'Bold / dark',
  blurb: 'Coral on charcoal, uppercase title',
  bg: '#14161B',
  panel: 'transparent',
  panelEdge: 'transparent',
  distFill: '#232830',
  distStroke: '#373D49',
  distSW: 1.0,
  accent: '#E2574B',
  accentDark: '#F2A69D',
  hiSW: 1.4,
  ink: '#ECEEF1',
  sub: '#99A1AD',
  faint: '#69707C',
  header: '#FFFFFF',
  num: '#828A97',
  numHalo: '#232830',
  insetFill: '#20242C',
  insetStroke: '#3A414C',
  titleFont: "'Archivo', system-ui, sans-serif",
  titleWeight: 800,
  titleSize: 50,
  titleTransform: 'uppercase',
  titleSpacing: '0.5px',
  bodyFont: "'IBM Plex Sans', system-ui, sans-serif",
  monoFont: "'IBM Plex Mono', ui-monospace, monospace",
  hiLabel: '#FFFFFF',
  hiHalo: '#14161B',
  shadow: 'none',
};

export const themes = [themeA, themeB, themeC];
